export const FETCH_START = 'fetchStart'
export const FETCH_END = 'fetchEnd'
export const FETCH_POSTS = 'fetchPosts'
export const FETCH_POST = 'fetchPost'
export const FETCH_PAGES = 'fetchPages'
export const FETCH_PAGE = 'fetchPage'
export const FETCH_PLAYLISTS = 'fetchPlayLists'
export const FETCH_PLAYLIST = 'fetchPlayList'
export const FETCH_TOPICS = 'fetchTopics'
export const CHANGE_LAYOUT = 'changeLayout'
export const LOGIN = 'login'
export const REGISTER = 'register'
export const LOGOUT = 'logout'
export const CHECK_AUTH = 'checkAuth'

