export const SET_POSTS = 'setPosts'
export const SET_POST = 'setPost'
export const SET_PAGES = 'setPages'
export const SET_PAGE = 'setPage'
export const SET_LAYOUT = 'setLayout'
export const SET_PLAYLISTS = 'setPlayLists'
export const SET_PLAYLIST = 'setPlayList'
export const SET_TOPICS = 'setTopics'
