# Generated by Django 3.0.3 on 2020-07-10 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_url', models.URLField(unique=True)),
                ('posts_url', models.URLField(unique=True)),
                ('post_tag', models.CharField(max_length=200)),
                ('link_tag', models.CharField(max_length=200)),
                ('title_tag', models.CharField(max_length=200)),
                ('image_tag', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='websites/')),
                ('language', models.CharField(choices=[('vi', 'Việt Nam'), ('en', 'English')], default='vi', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('subscribe', models.ManyToManyField(related_name='subscribes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('link', models.URLField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('saved', models.ManyToManyField(related_name='posts_saved', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.Website')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
