# Generated by Django 3.0.3 on 2020-07-10 09:49

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('blog', '0002_auto_20200710_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='websites', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
