# Generated by Django 3.0.3 on 2020-07-10 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_website_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='root_url',
        ),
    ]
