# Generated by Django 3.0.3 on 2020-07-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_website_root_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='max_post',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
