# Generated by Django 3.0.3 on 2020-07-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_website_max_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
