# Generated by Django 3.0.3 on 2020-07-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_website_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('created',)},
        ),
        migrations.AddField(
            model_name='website',
            name='content_image_tag',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
