# Generated by Django 3.0.3 on 2020-07-11 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200711_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='saved',
            new_name='users_saved',
        ),
    ]
