# Generated by Django 3.0.3 on 2020-07-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200719_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
