# Generated by Django 3.0.3 on 2020-07-20 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200720_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='websites', to='blog.Topic'),
        ),
    ]
