# Generated by Django 3.0.3 on 2020-07-20 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_website_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='users_saved',
            new_name='users_like',
        ),
    ]
