# Generated by Django 3.0.3 on 2020-07-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200722_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='status',
            field=models.CharField(choices=[('public', 'Công khai'), ('private', 'Ẩn')], default='public', max_length=10),
        ),
    ]
