# Generated by Django 3.0.3 on 2020-08-11 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_social_websites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='websites',
        ),
        migrations.CreateModel(
            name='LinkSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True)),
                ('social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Social')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Website')),
            ],
        ),
        migrations.AddField(
            model_name='social',
            name='websites',
            field=models.ManyToManyField(blank=True, null=True, related_name='socials', through='blog.LinkSocial', to='blog.Website'),
        ),
    ]
