# Generated by Django 3.0.3 on 2020-08-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20200811_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='websites',
            field=models.ManyToManyField(related_name='socials', through='blog.LinkSocial', to='blog.Website'),
        ),
    ]
